name: AV DB Build on Push

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container: 
      image: gcr.io/kaniko-project/executor:debug
    steps:
    - uses: actions/checkout@v1
    - name: Add GitHub push credentials
      run: echo "{\"auths\":{\"docker.pkg.github.com\":{\"auth\":\"${{ secrets.REGISTRY_PUSH_TOKEN }}\"}}}" > /kaniko/.docker/config.json
    - name: Image build
      run:  /kaniko/executor --context . --destination docker.pkg.github.com/luborpetr/clamav4pipeline/clamav4pipeline:latest
