name: AV DB Build Cheduled

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container: 
      image: gcr.io/kaniko-project/executor:debug
    steps:
    - uses: actions/checkout@v1
    - run: mkdir /workspace
    - run:  /kaniko/executor --context . --no-push
